### ISSUE TITLE
Checklist about Ant releases

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cm-ant#22]
@hippo-an (cc. @seokho-son @ish-hcc @dev4unet)

안녕하세요.

📅 Ant v0.2.x 릴리스 일정을 ~11/21(목)으로 조정 및 안내드립니다.

앞서 릴리스된 서브시스템들의 버전을 참고하셔서 Ant 릴리스 추진을 진행하여 주십시오. 진행하시면서 Ant에서 활용하는 서브시스템에서 개선할 사항이 있으면 해당 저장소에 이슈로 매달아 주시면 될 것 같습니다.

🙋 먼저, 관련한 이슈가 있으신 경우 댓글로 남겨주시기 바랍니다.

☑️ 아래 사항들에 대해 추진을 부탁드리며, 완료된 항목들은 Checked 처리하여 주십시오.
* [x] Ant 개발 및 테스트
* [x] Ant 관련 서브시스템과 통합 테스트 ([Sequence Diagram](https://github.com/cloud-barista/cloud-migrator/blob/main/docs/sequence-diagrams-for-user-scenarios.md) 참고 및 개선)
* [x] Ant 실행 지원
* [x] Ant 문서화
* [x] Ant 릴리스
각 항목별 자세한 사항은 아래 링크의 "저장소별 추진사항"을 참고하시면 될 것 같습니다.
Ref: https://github.com/cloud-barista/cloud-migrator/issues/11

아울러, 릴리스 이후 상위/타 서브시스템에서의 통합 및 테스트가 진행됩니다. 이 부분에 대해 미리 협조를 부탁드립니다.

(참고)
이번 Cloud-Migrator v0.3.0 통합 및 릴리스는 두 가지 측면에서 진행됩니다.

* 컴퓨팅 인프라 마이그레이션: Cloud-Migration portal에서 3종 클라우드로, 3종 자원에 대해 마이그레이션을 수행할 수 있어야 함
* SW 마이그레이션: 기능 개발, 테스트 및 통합 추진 (portal 통합 대상 X)

**Comment by hippo-an** [comment]
@yunkon-kim 
문서 및 wiki 업데이트, 기능 테스트 및 서브 시스템과 테스트 완료 후 0.2.7 릴리즈 진행했습니다.

**Comment by yunkon-kim** [comment]
@hippo-an 고생 많으셨습니다!!  :-)
